name: Update Ad List

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 8 * * 4' # 3 AM Detroit time in UTC


jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x ./combine_adlists.sh

      - name: Run Ad List Script
        run: ./combine_adlists.sh

      - name: Commit and Push Changes
        run: |
            git config --local user.name "github-actions"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add blocklist.txt
            git commit -m "Updated blocklist.txt [$(date +'%Y-%m-%d %H:%M:%S')]"
            git push

          
